/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 6.0.0   2016-10-24

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include <stdio.h>
#include <math.h>
#include "stm32l1xx.h"
#include "vrs_cv5.h"

// premenna na ulozenie hodnoty AD prevodu
volatile int ADC1_prevod = 0;
// vlajka na prepinanie medzi formatom vypisu
volatile unsigned char Format_FLAG = 0;

int main(void) {

	  /**
	  *  IMPORTANT NOTE!
	  *  See the <system_*.c> file and how/if the SystemInit() function updates
	  *  SCB->VTOR register. Sometimes the symbol VECT_TAB_SRAM needs to be defined
	  *  when building the project if code has been located to RAM and interrupts
	  *  are used. Otherwise the interrupt table located in flash will be used.
	  *  E.g.  SCB->VTOR = 0x20000000;
	  */

	  /**
	  *  At this stage the microcontroller clock setting is already configured,
	  *  this is done through SystemInit() function which is called from startup
	  *  file (startup_stm32l1xx_hd.s) before to branch to application main.
	  *  To reconfigure the default setting of SystemInit() function, refer to
	  *  system_stm32l1xx.c file
	  */

	// zavolame inicializacne funkcie
	LED_init();
	NVIC_init();
	USART_init();
	ADC_init();

	// premenna na uchovanie prevedeneho cisla
	char strADCNum[5];	// max 4095 + '\0'
	char strADCVol[5];	// X.XX + '\0'

	// hlavna slucka programu
	while (1) {
		// blikaj LED frekvenciou na zaklade hodnoty z AD prevodnika
		blikaj(ADC1_prevod);
		// podla vlajky menime format vypisu
		if(Format_FLAG){
			// nutny prepocet na vhodny format pre odoslanie
			float napatie = 3.3*(ADC1_prevod/4095.0);
			int Ccast = napatie;
			float zvysok = napatie - Ccast;
			int Dcast = trunc(zvysok*100);	// pre dve desatinne cisla
			// konverzia napatia na string
			sprintf(strADCVol, "%d.%d", Ccast, Dcast);
			// odosli po seriovej linke
			SendUSART2(strADCVol);
			SendUSART2("V\n\r");
		}
		else{
			// konverzia cisla na string
			sprintf(strADCNum, "%d", ADC1_prevod);
			// odosli po seriovej linke
			SendUSART2(strADCNum);
			SendUSART2("\n\r");
		}
	}
	return 0;
}

// funkcia prerusenia z ADC prevodnika
void ADC1_IRQHandler(void) {
	if (ADC1->SR & ADC_SR_EOC) {
		ADC1_prevod = ADC1->DR;
	}
}

// funkcia prerusenia USART2
void USART2_IRQHandler(void) {
	uint8_t pom = 0;
	// ak ak sme prijali data
	if (USART_GetITStatus(USART2, USART_IT_RXNE) != RESET) {
		// prijate data
		pom = USART_ReceiveData(USART2);
		// ak je prijaty znak 'm'
		if(pom == 'm'){
			// zmenime vlajku formatu vypisu na seriovej linke
			if(Format_FLAG==1){
				Format_FLAG = 0;
			}
			else{
				Format_FLAG = 1;
			}
		}
		// vynulujeme vlajku prerusenia
		USART_ClearITPendingBit(USART2, USART_IT_RXNE);
	}
}

#ifdef  USE_FULL_ASSERT

/**
 * @brief  Reports the name of the source file and the source line number
 *   where the assert_param error has occurred.
 * @param  file: pointer to the source file name
 * @param  line: assert_param error line source number
 * @retval None
 */
void assert_failed(uint8_t* file, uint32_t line)
{
	/* User can add his own implementation to report the file name and line number,
	 ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

	/* Infinite loop */
	while (1)
	{
	}
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func,
		const char *failedexpr) {
	while (1) {
	}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr) {
	__assert_func(file, line, NULL, failedexpr);
}
